In [ ]:
import numpy as np

# Main statistical characteristics

In [4]:
a = [2, 1, 3, 4, 2, 6, 4, 0, 1, 1, 3, 3, 4, 1, 1, 5, 5, 2, 1, 3]

In [7]:
# extending a list
7 * [1,2]

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [9]:
# To work with vectors, we can convert them into numpy arrays
np.array([1,2])

array([1, 2])

In [11]:
# multiplies the inside of the array by two
# does not multiply instances
2 * np.array([1,2])

array([2, 4])

## Task 1.1
Convert the list a defined above to a Numpy array, reassign the result again to the variable a to get the following output

a

array([2, 1, 3, 4, 2, 6, 4, 0, 1, 1, 3, 3, 4, 1, 1, 5, 5, 2, 1, 3])


In [13]:
a = np.array(a)
a

array([2, 1, 3, 4, 2, 6, 4, 0, 1, 1, 3, 3, 4, 1, 1, 5, 5, 2, 1, 3])

### Mean

In [22]:
# and we want to create the mean for it, we do:
mean_a = np.mean(a)
mean_a


np.float64(2.6)

This has taken the a array and created the numpy float 2.6 above

## Population variance and standard deviation
To calculate the population variance of a, i.e. the quantity

 

we use np.var method and to calculate the population standard deviation 
 we use np.std method. For example,

In [23]:
np.var(a)

np.float64(2.6399999999999997)

or

In [24]:
float(np.var(a))

2.6399999999999997

This is faster than doing this the longhand:

In [25]:
sum((a - np.mean(a))**2)/len(a)

np.float64(2.64)

np.mean(a) takes away a from all of the intigers in this array

## Task 1.3
Find the standard deviation of a. The answer should be:
1.624807680927192

In [27]:
np.std(a)

np.float64(1.624807680927192)

### Sample variance and standard deviation
To do for the pupulation, we can denote the delta degrees of freedom, which for the variance and standard deviation indicates the n in the denominator. Passing 0, or leaving blank the ddof in var means that it var or std will be a sample, otherwise ddof=1 will show the population variants

In [28]:
np.var(a, ddof = 1)

np.float64(2.7789473684210524)

Notice how this shrinks the denominator, increasing the value

In [29]:
np.var(a, ddof = 1) == np.var(a)*20/19

np.True_

## Task 1.4
Find the sample standard deviation for a using an analogy with the previous commands. Check the answer.

1.6670175069329813

In [35]:
np.std(a)

np.float64(1.624807680927192)